"""PR-01: the buying desk's intake bundle, judged on the transaction it landed on.

Registered exactly the way every rule since Step 5 has been - a function under an identifier,
with a leg requirement. The orchestrator, the context and the exception hook are untouched by it.

There is no configured threshold here, and that is deliberate rather than an omission. Every
other completeness check in the platform reads a ratio because a territory pack is negotiable;
this one is not. A purchase deal is an invoice, a packing list and a weight slip, and "two of the
three will do" is not a tolerance anybody could set responsibly.
"""

from __future__ import annotations

from app.models.enums import (
    PURCHASE_BUNDLE_ITEMS,
    PURCHASE_BUNDLE_LABELS,
    PurchaseBundleItem,
    RuleSeverity,
)
from app.services.purchase_intake import status_for
from app.services.rules.catalog import CheckKey, RuleId
from app.services.rules.registry import RuleContext, RuleOutcome, not_applicable, register


@register(RuleId.PR_01, requires_legs=frozenset({"purchase"}))
async def evaluate_purchase_bundle(context: RuleContext) -> list[RuleOutcome]:
    if context.leg("purchase") is None:
        return not_applicable(RuleId.PR_01, "This transaction carries no purchase leg.")

    status = status_for(context.documents)

    # The rule is about how a deal *arrives*, so it only judges a transaction that is genuinely
    # arriving as a bundle. A packing list or a weight slip is what says so: both are distinctive
    # to the buying desk's intake, and neither reaches this platform any other way.
    #
    # An invoice on its own is deliberately not enough to start this rule. That is what a
    # transaction registered by hand on the workspace looks like, and what every purchase deal
    # recorded before this vocabulary existed looks like; judging those as short of a weighbridge
    # ticket nobody ever attached would open a case against paperwork that was never coming.
    if not any(
        row.received and row.item != PurchaseBundleItem.INVOICE.value for row in status.items
    ):
        return not_applicable(
            RuleId.PR_01,
            "No packing list or weight slip has arrived for this batch, so it is not being "
            "assembled as a purchase intake bundle and there is nothing to check it against.",
        )

    missing = status.missing

    outcomes = [
        RuleOutcome(
            rule_id=RuleId.PR_01,
            check_key=CheckKey.PURCHASE_BUNDLE_COMPLETE,
            passed=status.complete,
            severity=RuleSeverity.HARD.value,
            field_name="purchase_bundle",
            expected_value=f"{len(PURCHASE_BUNDLE_ITEMS)} of {len(PURCHASE_BUNDLE_ITEMS)} documents",
            actual_value=status.summary(),
            message=(
                "The purchase bundle is complete: supplier invoice, packing list and weight slip "
                "are all attached."
                if status.complete
                else "The purchase bundle is incomplete. Still missing: "
                + ", ".join(PURCHASE_BUNDLE_LABELS.get(entry, entry).lower() for entry in missing)
                + "."
            ),
        )
    ]

    if status.unexpected:
        outcomes.append(
            RuleOutcome(
                rule_id=RuleId.PR_01,
                check_key=CheckKey.PURCHASE_BUNDLE_PURITY,
                passed=False,
                severity=RuleSeverity.HARD.value,
                field_name="document_type",
                expected_value=", ".join(PURCHASE_BUNDLE_ITEMS),
                actual_value=", ".join(
                    sorted({row.document_type or "unknown" for row in status.unexpected})
                ),
                message=(
                    "This purchase transaction carries paperwork a purchase bundle never does: "
                    + ", ".join(sorted(row.filename for row in status.unexpected))
                    + ". The purchase contract is generated by this platform, never received."
                ),
            )
        )

    return outcomes
