import { ArrowUpRight, Download, Sparkles } from "lucide-react";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  REPORT_FORMAT_LABELS,
  REPORT_STREAM_LABELS,
  REPORT_TYPE_CHIP,
  REPORT_TYPE_LABELS,
  drillThroughHref,
  formatDay,
  formatFigure,
  formatMoment,
  type ReportFormat,
  type ReportType,
} from "@/lib/analytics";
import type { ReportDetail, ReportSection } from "@/lib/api-client";
import { TRANSACTION_STATUS_LABELS, type TransactionStatus } from "@/lib/transactions";
import { cn } from "@/lib/utils";

export interface ReportViewerProps {
  report: ReportDetail;
}

/**
 * The report, on screen, with a way through to the rows behind every figure in it.
 *
 * This is the point of the whole screen. A number here is never a static figure: each one carries
 * the filters it was computed under, and this component turns those into a link into the
 * Transactions, Exceptions, Approvals, Shipments or Documents list, pre-filtered to reproduce
 * exactly that number. Somebody reading "eleven open exceptions" can be looking at the eleven.
 *
 * What is rendered is the report as it was produced, at the moment stamped on it, which is also
 * what the downloadable file contains. The links go to the live queues, so a figure and its rows
 * can differ where work has happened since - which is why the generated-at stamp sits at the top
 * of the page rather than in a footnote.
 */
export function ReportViewer({ report }: ReportViewerProps) {
  const content = report.content;

  return (
    <div className="space-y-6">
      <section className="rounded-medium border-thin border-border bg-elevation-default shadow-raised p-5">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="min-w-0 space-y-1.5">
            <div className="flex flex-wrap items-center gap-2">
              <Badge
                variant="outline"
                className={cn(REPORT_TYPE_CHIP[report.report_type as ReportType])}
              >
                {REPORT_TYPE_LABELS[report.report_type as ReportType] ?? report.report_type}
              </Badge>
              <h2 className="text-base font-semibold text-foreground">{content.title}</h2>
            </div>
            <p className="max-w-2xl text-sm leading-relaxed text-muted-foreground">
              {content.description}
            </p>
          </div>
          {report.download_url ? (
            <Button asChild size="sm" variant="outline">
              {/* A short-lived signed link through the authenticated file route, minted for this
                  request. There is no permanent path to a stored report. */}
              <a href={report.download_url} target="_blank" rel="noreferrer">
                <Download className="mr-1.5 h-3.5 w-3.5" aria-hidden="true" />
                Download the{" "}
                {REPORT_FORMAT_LABELS[report.output_format as ReportFormat] ??
                  report.output_format}
              </a>
            </Button>
          ) : null}
        </div>

        <dl className="mt-5 grid gap-x-8 gap-y-3 border-t border-border pt-4 sm:grid-cols-2 xl:grid-cols-4">
          <Meta label="Generation reference">
            <span className="font-mono text-secondary">{content.generation_reference}</span>
          </Meta>
          <Meta label="Period covered">
            {formatDay(content.period.start)} → {formatDay(content.period.end)}
          </Meta>
          <Meta label="Business stream">
            {REPORT_STREAM_LABELS[content.stream] ?? content.stream}
          </Meta>
          <Meta label="Status filter">
            {content.status_filter
              ? (TRANSACTION_STATUS_LABELS[content.status_filter as TransactionStatus] ??
                content.status_filter)
              : "Every status"}
          </Meta>
          <Meta label="Generated at">{formatMoment(content.generated_at)}</Meta>
          <Meta label="Generated by">
            {report.scheduled
              ? "On schedule, by the platform"
              : (content.generated_by ?? "Account no longer on the platform")}
          </Meta>
          <Meta label="Template">{content.template_key}</Meta>
          <Meta label="Audit record">
            {report.audit_event_id ? (
              <span className="font-mono text-xs">{report.audit_event_id}</span>
            ) : (
              "-"
            )}
          </Meta>
        </dl>

        <p className="mt-4 rounded-medium border-thin border-border bg-elevation-sunken px-4 py-3 text-xs leading-relaxed text-muted-foreground">
          {report.distribution_note}
        </p>
      </section>

      {content.sections.map((section) => (
        <Section key={section.key} section={section} />
      ))}

      {content.disclosures.length > 0 ? (
        <section className="rounded-lg border border-border bg-surface p-5">
          <h3 className="text-sm font-semibold text-foreground">How to read this report</h3>
          <ul className="mt-3 space-y-2">
            {content.disclosures.map((note) => (
              <li key={note} className="text-xs leading-relaxed text-muted-foreground">
                {note}
              </li>
            ))}
          </ul>
        </section>
      ) : null}
    </div>
  );
}

function Meta({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="min-w-0">
      <dt className="text-xs font-medium uppercase tracking-widest text-muted-foreground">
        {label}
      </dt>
      <dd className="mt-1 truncate text-sm text-foreground">{children}</dd>
    </div>
  );
}

function Section({ section }: { section: ReportSection }) {
  return (
    <section className="rounded-medium border-thin border-border bg-elevation-default shadow-raised p-5">
      <h3 className="text-sm font-semibold text-foreground">{section.title}</h3>
      {section.description ? (
        <p className="mt-1 max-w-3xl text-xs leading-relaxed text-muted-foreground">
          {section.description}
        </p>
      ) : null}

      <div className="mt-4">
        {section.kind === "ai_summary" ? <AiSummary section={section} /> : null}
        {section.kind === "kpi_grid" ? <FigureGrid section={section} /> : null}
        {section.kind === "breakdown" || section.kind === "table" ? (
          <RowTable section={section} />
        ) : null}
        {section.kind === "note" ? (
          <p className="text-sm text-foreground">{section.text}</p>
        ) : null}
      </div>

      {section.note ? (
        <p className="mt-4 border-t border-border pt-3 text-xs leading-relaxed text-muted-foreground">
          {section.note}
        </p>
      ) : null}
    </section>
  );
}

/**
 * The one part of a report the model wrote, labelled as such and never blended into the figures.
 *
 * When the summary could not be produced, the section says so and the report is otherwise
 * complete: nothing below it depends on the paragraph existing.
 */
function AiSummary({ section }: { section: ReportSection }) {
  if (!section.text) {
    return (
      <p className="rounded-md border border-dashed border-border bg-surface px-4 py-3 text-sm text-muted-foreground">
        {section.unavailable_reason ??
          "The AI summary is unavailable for this report. Every figure below it is computed by the platform and is unaffected."}
      </p>
    );
  }
  return (
    <div className="rounded-md border border-pill-purple-border bg-pill-purple-bg px-space-200 py-space-150">
      <p className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-widest text-accent">
        <Sparkles className="h-3.5 w-3.5" aria-hidden="true" />
        AI-generated summary
      </p>
      <p className="mt-2 text-sm leading-relaxed text-foreground">{section.text}</p>
      <p className="mt-2 text-xs text-muted-foreground">
        Written by the AI assistant from the figures in this report. Every figure itself is
        computed by the platform, not by the model.
      </p>
    </div>
  );
}

function FigureGrid({ section }: { section: ReportSection }) {
  const figures = section.figures ?? [];
  if (figures.length === 0) {
    return <p className="text-sm text-muted-foreground">Nothing to report for this period.</p>;
  }

  return (
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
      {figures.map((figure) => {
        const href = drillThroughHref(figure);
        return (
          <div key={figure.key} className="rounded-medium border-thin border-border bg-elevation-sunken p-4">
            <p className="text-xs font-medium uppercase tracking-widest text-muted-foreground">
              {figure.label}
            </p>
            <p className="mt-1.5 text-2xl font-semibold tabular-nums text-foreground">
              {formatFigure(figure.value, figure.unit)}
            </p>
            {figure.note ? (
              <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">{figure.note}</p>
            ) : null}
            {href ? (
              <Link
                href={href}
                className="mt-2 inline-flex items-center gap-1 text-xs text-secondary underline-offset-4 hover:underline"
              >
                View transactions
                <ArrowUpRight className="h-3 w-3" aria-hidden="true" />
              </Link>
            ) : null}
          </div>
        );
      })}
    </div>
  );
}

function RowTable({ section }: { section: ReportSection }) {
  const columns = section.columns ?? [];
  const rows = section.rows ?? [];

  if (rows.length === 0) {
    return <p className="text-sm text-muted-foreground">Nothing in this period.</p>;
  }

  return (
    <div className="space-y-3">
      <div className="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              {columns.map((column) => (
                <TableHead key={column.key}>{column.label}</TableHead>
              ))}
              <TableHead className="text-right">Source</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((row, index) => {
              const href = drillThroughHref({
                target: (row.target as string | undefined) ?? section.target,
                filters: (row.filters as Record<string, unknown> | undefined) ?? section.filters,
              });
              const transactionId = row.transaction_id as string | undefined;
              return (
                <TableRow key={`${section.key}-${index}`}>
                  {columns.map((column) => (
                    <TableCell key={column.key} className="whitespace-nowrap">
                      {renderCell(row[column.key])}
                    </TableCell>
                  ))}
                  <TableCell className="text-right">
                    {transactionId ? (
                      <Link
                        href={`/transactions/purchase/${transactionId}`}
                        className="inline-flex items-center gap-1 text-xs text-secondary underline-offset-4 hover:underline"
                      >
                        Open batch
                        <ArrowUpRight className="h-3 w-3" aria-hidden="true" />
                      </Link>
                    ) : href ? (
                      <Link
                        href={href}
                        className="inline-flex items-center gap-1 text-xs text-secondary underline-offset-4 hover:underline"
                      >
                        View transactions
                        <ArrowUpRight className="h-3 w-3" aria-hidden="true" />
                      </Link>
                    ) : (
                      <span className="text-xs text-muted-foreground">-</span>
                    )}
                  </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </div>

      {section.truncated ? (
        <p className="text-xs text-muted-foreground">
          Showing {rows.length} of {section.total_matching} matching transactions. The full set is
          in the Transactions list behind the link on any row.
        </p>
      ) : null}
    </div>
  );
}

function renderCell(value: unknown): string {
  if (value === null || value === undefined || value === "") return "-";
  if (typeof value === "number") return new Intl.NumberFormat("en-GB").format(value);
  if (typeof value === "boolean") return value ? "yes" : "no";
  return String(value);
}
